from . import auth
from . import domain
from . import health
from . import uploads
from . import anemia
from . import breast_cancer
from . import malaria
from . import dementia
from . import prediction
from . import dashboard
from . import recent_predictions
from . import disease_distribution
from . import confidence_trend
from . import reports
from . import patient_appointments
from . import doctor
